name: shape-processing-rnns
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.7.0
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - numpy=1.23.5
  - pip=23.0.1
  - python=3.10.9
  - torchvision=0.15.0
  - wandb=0.14.0
  - pkg-config=0.29.2
  - libjpeg-turbo=2.1.4
  - opencv=4.7.0
  - numba=0.56.4
  - pandas=1.5.3
  - ipykernel=6.19.2
  - pip:
      - tqdm==4.65.0
      - cupy-cuda11x==11.6.0
      - ffcv==1.0.2